parameters:
#    sgii.example.class: sgii\sgiiBundle\Example
    security.class: sgii\sgiiBundle\Services\SecurityService

services:
#    sgii.example:
#        class: %sgii.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    security:
        class: %security.class%
        arguments: ["@doctrine", "@session"]
