parameters:
    security.class: sgii\sgiiBundle\Services\SecurityService
    validate.class: sgii\sgiiBundle\Services\ValidateService
    instrumentos.class: sgii\sgiiBundle\Services\InstrumentosService
    queries.class:  sgii\sgiiBundle\Services\GenericQueriesService
    import.class:  sgii\sgiiBundle\Services\ImportService
    mail.class:  sgii\sgiiBundle\Services\MailService

services:
# SERVICES
    security:
        class: %security.class%
        arguments: ["@doctrine", "@session"]
    validate:
        class: %validate.class%
        arguments: ["@validator"]
    queries:
        class: %queries.class%
        arguments: ["@doctrine", "@session"]
    instrumentos:
        class: %instrumentos.class%
        arguments: ["@doctrine", "@session"]
    import:
        class: %import.class%
        arguments: ["@service_container"]
    mail:
        class: %mail.class%
        arguments: ["@mailer", "@templating"]
        
    kernel.listener.listener:
        class: sgii\sgiiBundle\EventListener\sgiiExceptionListener
        arguments: ["@templating", "@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
        
# TWIG EXTENSIONS        
    twig.extension.GravatarExtension:
        class: sgii\sgiiBundle\Services\TwigExtensions\GravatarExtension
        tags:
                - { name: twig.extension }
