parameters:
    security.class: sgii\sgiiBundle\Services\SecurityService
    validate.class: sgii\sgiiBundle\Services\ValidateService
    instrumentos.class: sgii\sgiiBundle\Services\InstrumentosService
    queries.class:  sgii\sgiiBundle\Services\GenericQueriesService

services:
# SERVICES
    security:
        class: %security.class%
        arguments: ["@doctrine", "@session"]
    validate:
        class: %security.class%
    queries:
        class: %queries.class%
        arguments: ["@doctrine", "@session"]
    instrumentos:
        class: %instrumentos.class%
        arguments: ["@doctrine", "@session"]
        
        
    kernel.listener.listener:
        class: sgii\sgiiBundle\EventListener\sgiiExceptionListener
        arguments: ["@templating", "@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
        
# TWIG EXTENSIONS        
    twig.extension.GravatarExtension:
        class: sgii\sgiiBundle\Services\TwigExtensions\GravatarExtension
        tags:
                - { name: twig.extension }
